### ISSUE TITLE
graphql-query from API Service Layer to check for Quest Completion

### ISSUE THREAD

**Issue by roshaans** [Quest-Protocol/questverse-monorepo#17]
Write an indexer function + related tests that query this server:  `https://near-queryapi.api.pagoda.co`
Lets say you get a payload like the following: `{accountId: "matt.near", quest_id: 23233}`

### Assume that the following exists

> We will use https://github.com/Quest-Protocol/questverse-monorepo/issues/15 the following issue to get the indexer that you should call. 

In this case, it will return to you -> `roshaan.near/quest_dao_join_quest` which is an indexer accessible via this [link](https://near.org/#/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=roshaan.near/quest_dao_join_quest)

Using a graphql-client you should always make the same exact query. Notice that we need to craft the table name from the `indexer_config_id`
roshaan.near/quest_dao_join_quest

1.  change (`.` and `/`) into `_` and add "quest_tracker" to the end of it to retrieve the table name. 
2. We pass in the account_id given to us by the payload. 
3. return errors if any errors are encountered
4. If no errors, check the `is_completed` and see if it is true. If true, sign the payload. 
5. If not true, dont sign the payload and return error message saying that you have no completed the quest. Possibly also return back the query results. 

```graphql
query QueryQuestCompletion($account_id: String = "") {
  roshaan_near_quest_dao_join_quest_quest_tracker(
    where: {account_id: {_eq: $account_id}}
  ) {
    account_id
    block_height
    is_completed
  }
}
```

Note: 

To test this query, use the following [playground link](https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Fnear-queryapi.api.pagoda.co%2Fv1%2Fgraphql&query=query+QueryQuestCompletion%28%24account_id%3A+String+%3D+%22%22%29+%7B%0A++roshaan_near_quest_dao_join_quest_quest_tracker%28%0A++++where%3A+%7Baccount_id%3A+%7B_eq%3A+%24account_id%7D%7D%0A++%29+%7B%0A++++account_id%0A++++block_height%0A++++is_completed%0A++%7D%0A%7D)

Just make sure to specify the following header `x-hasura-role: roshaan_near`. 

<img width="1495" alt="image" src="https://github.com/Quest-Protocol/questverse-monorepo/assets/25015977/e46bb23d-9373-4277-856a-a2183cd89b76">

**Comment by friendlymatthew** [comment]
Ok -- let me know if I understand this correctly:

Given: `{accountId: "matt.near", quest_id: 23233}`, https://github.com/Quest-Protocol/questverse-monorepo/issues/15 will return a `indexer id`. An example of an `indexer id` looks like:`roshaan.near/quest_dao_join_quest`.

transform indexer_id to a graphql query: roshaan_near_quest_dao_join_quest_quest_tracker following: 

> 1. change (`.` and `/`) into `_` and add "quest_tracker" to the end of it to retrieve the table name.

Then we use the `graphql_client` to query and do the following logic:
> 2. We pass in the account_id given to us by the payload.
> 3. return errors if any errors are encountered
> 4. If no errors, check the `is_completed` and see if it is true. If true, sign the payload.
> 5. If not true, dont sign the payload and return error message saying that you have no completed the quest. Possibly also return back the query results.

**Comment by roshaans** [comment]
> 3\. eturn errors if any errors are encountered

This is right.

**Comment by friendlymatthew** [comment]
> This is right. 

I love it when we communicate like this
